monitor.bluez.rules = [
  {
    matches = [
       {
         ## This matches all bluetooth devices.
         device.name = "~bluez_card.*"
       }
     ]
     actions = {
       update-props = {
        bluez5.bap.force-target-latency = "high-reliability"
       }
     }
  }
]
