[tool.poetry]
name = "autopts"
version = "0.1.0"
description = "Auto PTS tooling"
authors = ["Jakub Marciniak <marciniakjakub93@gmail.com>"]
readme = "README.md"
packages = [
    { include = "autopts" }
]

[tool.poetry.dependencies]
python = ">=3.10"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.2.0"
ruff = "^0.11.3"
isort = "^6.0.1"

[tool.poetry.scripts]
fix-style = "autopts.poetry_tools:fix_style"
check-isort = "autopts.poetry_tools:check_isort"

[tool.isort]
profile = "black"
line_length = 127
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
lines_after_imports = 2
skip = [
    ".venv",
    "build",
    "dist",
    "tmp",
    "__pycache__",
    "tests/__pycache__"
]

skip_glob = ["*.egg-info"]

[tool.ruff]
line-length = 127
exclude = [
  ".venv",
  "build",
  "dist",
  "tmp",
  "__pycache__",
  "*.egg-info",
  "tests/__pycache__"
]
