[tool.ruff]
line-length = 127
exclude = [
  ".venv",
  "build",
  "dist",
  "tmp",
  "__pycache__",
  "*.egg-info",
  "tests/__pycache__"
]

[tool.ruff.lint]
select = ["F", "E", "W", "I", "UP", "ISC", "TID", "PT", "A", "PERF", "B"]
ignore = ["F841"] # F841 - there are a lot of variables that are not currently used in the repository but may be in internal tests
# select = ["E", "W", "F", "I", "UP", "C90", "PYI", "ISC", "TID"]
preview = true

[tool.ruff.lint.per-file-ignores]
"tools/generate_profile.py" = ["ISC001", "ISC002", "ISC003"]
"autoptsserver.py" = ["ALL"] # TODO: Review and refactor _dispatch_blocking for proper async compatibility.
#Current implementation relies on blocking queue polling with try-except inside a loop,
# which is not compliant with PEP8 and triggers linter warnings (e.g., PERF203).
# However, replacing this pattern would fundamentally change the logic and thread safety.
# Proper async adaptation or queue mechanism is required for a clean, PEP8-compliant solution.

