[tool.ruff]
line-length = 127
exclude = [
  ".venv",
  "build",
  "dist",
  "tmp",
  "__pycache__",
  "*.egg-info",
  "tests/__pycache__"
]

[tool.ruff.lint]
select = ["F", "E", "W", "I", "UP", "ISC"]
ignore = ["F841"] # F841 - there are a lot of variables that are not currently used in the repository but may be in internal tests
# select = ["E", "W", "F", "I", "UP", "C90", "PYI", "ISC", "TID"]
preview = true

[tool.ruff.lint.per-file-ignores]
"tools/generate_profile.py" = ["ISC001", "ISC002", "ISC003"]
