"""GATT test cases"""

try:
    from ptsprojects.testcase import TestCase, TestCmd, TestFunc, \
        TestFuncCleanUp
    from ptsprojects.zephyr.qtestcase import QTestCase

except ImportError: # running this module as script
    import sys
    sys.path.append("../..") # to be able to locate the following imports

    from ptsprojects.testcase import TestCase, TestCmd, TestFunc, \
        TestFuncCleanUp
    from ptsprojects.zephyr.qtestcase import QTestCase

from ptsprojects.zephyr.iutctl import get_zephyr
import btp


def decode_flag_name(flag, names_dict):
    """Returns string description that corresponds to flag"""

    decoded_str = ""
    sep = ", "

    for named_flag in sorted(names_dict.keys()):
        if (flag & named_flag) == named_flag:
            decoded_str += names_dict[named_flag] + sep

    if decoded_str.endswith(sep):
        decoded_str = decoded_str.rstrip(sep)

    return decoded_str

class Prop:
    """Properties of characteresic

    Specified in BTP spec:

    Possible values for the Properties parameter are a bit-wise of the
    following bits:

    0       Broadcast
    1       Read
    2       Write Without Response
    3       Write
    4       Notify
    5       Indicate
    6       Authenticated Signed Writes
    7       Extended Properties

    """
    broadcast     = 2 ** 0
    read          = 2 ** 1
    write_wo_resp = 2 ** 2
    write         = 2 ** 3
    nofity        = 2 ** 4
    indicate      = 2 ** 5
    auth_swrite   = 2 ** 6
    ext_prop      = 2 ** 7

    names = {
        broadcast     : "Broadcast",
        read          : "Read",
        write_wo_resp : "Write Without Response",
        write         : "Write",
        nofity        : "Notify",
        indicate      : "Indicate",
        auth_swrite   : "Authenticated Signed Writes",
        ext_prop      : "Extended Properties",
    }

    @staticmethod
    def decode(prop):
        return decode_flag_name(prop, Prop.names)

class Perm:
    """Permission of characteresic or descriptor

    Specified in BTP spec:

    Possible values for the Permissions parameter are a bit-wise of the
    following bits:

    0       Read
    1       Write
    2       Read with Encryption
    3       Write with Encryption
    4       Read with Authentication
    5       Write with Authentication
    6       Authorization

    """
    read        = 2 ** 0
    write       = 2 ** 1
    read_enc    = 2 ** 2
    write_enc   = 2 ** 3
    read_authn  = 2 ** 4
    write_authn = 2 ** 5
    authz       = 2 ** 6

    names = {
        read        : "Read",
        write       : "Write",
        read_enc    : "Read with Encryption",
        write_enc   : "Write with Encryption",
        read_authn  : "Read with Authentication",
        write_authn : "Write with Authentication",
        authz       : "Authorization"
    }

    @staticmethod
    def decode(perm):
        return decode_flag_name(perm, Perm.names)

def test_cases_server():
    """Returns a list of GATT Server test cases"""

    zephyrctl = get_zephyr()

    test_cases = [
        QTestCase("GATT", "TC_GAC_SR_BV_01_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read | Prop.write | Prop.nofity,
                            Perm.read | Perm.write, 'BBBB'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF' * 10),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAD_SR_BV_01_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)],
                  verify_wids = {17 : ("Please confirm IUT receive primary services", "Service = 0xAAAA")}),
       QTestCase("GATT", "TC_GAD_SR_BV_02_C",
                 [TestFunc(btp.core_reg_svc_gap),
                  TestFunc(btp.core_reg_svc_gatts),
                  TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                  TestFunc(btp.gatts_start_server),
                  TestFunc(btp.gap_adv_ind_on)],
                 verify_wids = {23 : ("Please confirm IUT have following primary services",
                                      "UUID= \'AAAA\'", "start handle = 0x0001", "end handle = 0x0001")}),
        QTestCase("GATT", "TC_GAD_SR_BV_03_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                   TestFunc(btp.gatts_add_inc_svc, 1),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)],
                  verify_wids = {24 : ("Attribute Handle = 0x0002",
                                       "Included Service Attribute handle = 0x0001", "End Group Handle = 0x0002",
                                       "Service UUID = 0xAAAA")}),
        QTestCase("GATT", "TC_GAD_SR_BV_04_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read | Prop.write | Prop.nofity,
                            Perm.read | Perm.write, 'bbbb'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)],
                  verify_wids = {25 : ("Please confirm IUT have following characteristics",
                                       "UUID= \'AAAA\'", "handle=0x0002")}),
        QTestCase("GATT", "TC_GAD_SR_BV_05_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read | Prop.write | Prop.nofity,
                            Perm.read | Perm.write, 'BBBB'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAD_SR_BV_06_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read | Prop.write | Prop.nofity,
                            Perm.read | Perm.write, 'BBBB'),
                   TestFunc(btp.gatts_add_desc, 2, Perm.read | Perm.write,
                            'CCCC'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BV_01_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read | Prop.write | Prop.nofity,
                            Perm.read | Perm.write, 'BBBB'),
                   TestFunc(btp.gatts_set_val, 2, '01234abc'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BI_01_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                   TestFunc(btp.gatts_add_char, 1, 0x00, 0x00, 'BBBB'),
                   TestFunc(btp.gatts_set_val, 2, '0123'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BI_02_C",
                  edit1_wids = {118 : "ffff"},
                  cmds = [
                      TestFunc(btp.core_reg_svc_gap),
                      TestFunc(btp.core_reg_svc_gatts),
                      TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                      TestFunc(btp.gatts_add_char, 1,
                               Prop.broadcast, Perm.write,
                               'BBBB'),
                      TestFunc(btp.gatts_set_val, 2, '0123'),
                      TestFunc(btp.gatts_start_server),
                      TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BI_05_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read | Perm.read_enc, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_set_enc_key_size, 2, 0x0f),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BV_03_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read | Prop.write | Prop.nofity,
                            Perm.read | Perm.write,
                            '0123456789abcdef0123456789abcdef'),
                   TestFunc(btp.gatts_set_val, 2, '0123'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BI_06_C",
                  edit1_wids = {111 : "BBBB", 110 : "0003"},
                  cmds = [TestFunc(btp.core_reg_svc_gap),
                          TestFunc(btp.core_reg_svc_gatts),
                          TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                          TestFunc(btp.gatts_add_char, 1, 0x00, 0x00, 'BBBB'),
                          TestFunc(btp.gatts_set_val, 2, '01234abc'),
                          TestFunc(btp.gatts_start_server),
                          TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BI_07_C",
                  edit1_wids = {119 : "BBBC"},
                  cmds = [TestFunc(btp.core_reg_svc_gap),
                          TestFunc(btp.core_reg_svc_gatts),
                          TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                          TestFunc(btp.gatts_add_char, 1,
                                   Prop.broadcast | Prop.read,
                                   Perm.read | Perm.write,
                                   'BBBB'),
                          TestFunc(btp.gatts_set_val, 2, '0123'),
                          TestFunc(btp.gatts_start_server),
                          TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BI_08_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.broadcast | Prop.read,
                            Perm.read | Perm.write,
                            'BBBB'),
                   TestFunc(btp.gatts_set_val, 2, '0123'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BI_11_C",
                  edit1_wids = {121 : "0003", 122 : "AA51"},
                  cmds = [TestFunc(btp.core_reg_svc_gap),
                          TestFunc(btp.core_reg_svc_gatts),
                          TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                          TestFunc(btp.gatts_add_char, 1,
                                   Prop.read,
                                   Perm.read | Perm.read_enc,
                                   'AA51'),
                          TestFunc(btp.gatts_set_val, 2, '0123'),
                          TestFunc(btp.gatts_set_enc_key_size, 2, 0x0f),
                          TestFunc(btp.gatts_start_server),
                          TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BV_04_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read | Prop.write | Prop.nofity,
                            Perm.read | Perm.write, 'BBBB'),
                   TestFunc(btp.gatts_set_val, 2, 'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)],
                  verify_wids = {52 : ("Please confirm IUT Handle=\'3\'",
                                       "characteristic value=\'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF\'")}),
        QTestCase("GATT", "TC_GAR_SR_BI_12_C",
                  edit1_wids = {110 : "0003"},
                  cmds = [TestFunc(btp.core_reg_svc_gap),
                          TestFunc(btp.core_reg_svc_gatts),
                          TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                          TestFunc(btp.gatts_add_char, 1, 0x00, 0x00, 'BBBB'),
                          TestFunc(btp.gatts_set_val, 2, 'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF'),
                          TestFunc(btp.gatts_start_server),
                          TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BI_13_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read | Prop.write | Prop.nofity,
                            Perm.read | Perm.write, 'BBBB'),
                   TestFunc(btp.gatts_set_val, 2, 'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BI_14_C",
                  edit1_wids = {118 : "ffff"},
                  cmds = [
                      TestFunc(btp.core_reg_svc_gap),
                      TestFunc(btp.core_reg_svc_gatts),
                      TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                      TestFunc(btp.gatts_add_char, 1,
                               Prop.read | Prop.write | Prop.nofity,
                               Perm.read | Perm.write, 'BBBB'),
                      TestFunc(btp.gatts_set_val, 2, 'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF'),
                      TestFunc(btp.gatts_start_server),
                      TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BI_17_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read | Perm.read_enc, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, 'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF'),
                   TestFunc(btp.gatts_set_enc_key_size, 2, 0x0f),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BV_05_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read | Perm.write, '2A00'),
                   TestFunc(btp.gatts_set_val, 2, '0123'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read | Perm.write, '2a01'),
                   TestFunc(btp.gatts_set_val, 4, '4567'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)],
                  verify_wids =  {56 : ("Please confirm IUT Handle pair", "0005", "0003", "value=\'45670123\'")}),
        QTestCase("GATT", "TC_GAR_SR_BI_18_C",
                  edit1_wids = {110 : "0003"},
                  cmds = [
                      TestFunc(btp.core_reg_svc_gap),
                      TestFunc(btp.core_reg_svc_gatts),
                      TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                      TestFunc(btp.gatts_add_char, 1,
                               Prop.write, Perm.write, 'BBB1'),
                      TestFunc(btp.gatts_set_val, 2, '0123'),
                      TestFunc(btp.gatts_add_char, 1,
                               Prop.read | Prop.write | Prop.nofity,
                               Perm.read | Perm.write, 'BBB2'),
                      TestFunc(btp.gatts_set_val, 4, '4567'),
                      TestFunc(btp.gatts_start_server),
                      TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BI_19_C",
                  edit1_wids = {118 : "ffff"},
                  cmds = [
                      TestFunc(btp.core_reg_svc_gap),
                      TestFunc(btp.core_reg_svc_gatts),
                      TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                      TestFunc(btp.gatts_add_char, 1,
                               Prop.write, Perm.write, 'BBB1'),
                      TestFunc(btp.gatts_set_val, 2, '0123'),
                      TestFunc(btp.gatts_add_char, 1,
                               Prop.read, Perm.read, 'BBB2'),
                      TestFunc(btp.gatts_set_val, 4, '4567'),
                      TestFunc(btp.gatts_add_char, 1,
                               Prop.read | Prop.write | Prop.nofity,
                               Perm.read | Perm.write, 'BBB3'),
                      TestFunc(btp.gatts_set_val, 6, '4567'),
                      TestFunc(btp.gatts_add_char, 1,
                               Prop.read | Prop.write | Prop.nofity,
                               Perm.read | Perm.write, 'BBB4'),
                      TestFunc(btp.gatts_set_val, 8, '4567'),
                      TestFunc(btp.gatts_start_server),
                      TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BI_22_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read, 'BBB1'),
                   TestFunc(btp.gatts_set_val, 2, '0123'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read | Perm.read_enc, 'BBB2'),
                   TestFunc(btp.gatts_set_val, 4, '4567'),
                   TestFunc(btp.gatts_set_enc_key_size, 4, 0x0f),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read, 'BBB3'),
                   TestFunc(btp.gatts_set_val, 6, '4567'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read, 'BBB4'),
                   TestFunc(btp.gatts_set_val, 8, '4567'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BV_06_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_add_desc, 2, Perm.read, 'AA52'),
                   TestFunc(btp.gatts_set_val, 4, 'FEDCBA9876543210'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)],
                  verify_wids = {52 : ("Please confirm IUT Handle=\'4\'", "value=\'FEDCBA9876543210\'")}),
        QTestCase("GATT", "TC_GAR_SR_BI_23_C",
                  edit1_wids = {110 : "0004"},
                  cmds = [
                      TestFunc(btp.core_reg_svc_gap),
                      TestFunc(btp.core_reg_svc_gatts),
                      TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                      TestFunc(btp.gatts_add_char, 1,
                               Prop.read, Perm.read, 'AA51'),
                      TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                      TestFunc(btp.gatts_add_desc, 2, 0x00, 'AA52'),
                      TestFunc(btp.gatts_set_val, 4, 'FEDCBA9876543210'),
                      TestFunc(btp.gatts_start_server),
                      TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BI_24_C",
                  edit1_wids = {118 : "0005"},
                  cmds = [
                      TestFunc(btp.core_reg_svc_gap),
                      TestFunc(btp.core_reg_svc_gatts),
                      TestFunc(btp.gatts_add_svc, 0, 'F000AA5004514000B123456789ABCDEF'),
                      TestFunc(btp.gatts_add_char, 1,
                               Prop.read, Perm.read, 'AA51'),
                      TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                      TestFunc(btp.gatts_add_desc, 2, Perm.read, 'AA52'),
                      TestFunc(btp.gatts_set_val, 4, 'FEDCBA9876543210'),
                      TestFunc(btp.gatts_start_server),
                      TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BI_25_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read,
                            'F000AA5104514000B123456789ABCDEF'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_add_desc, 2,
                            Perm.read | Perm.authz, 'AA52'),
                   TestFunc(btp.gatts_set_val, 4, 'FEDCBA9876543210'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BI_26_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0,
                            'F000AA5004514000B123456789ABCDEF'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read,
                            'F000AA5104514000B123456789ABCDEF'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_add_desc, 2,
                            Perm.read | Perm.read_authn,
                            'F000AA5204514000B123456789ABCDEF'),
                   TestFunc(btp.gatts_set_val, 4, 'FEDCBA9876543210'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BI_27_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_add_desc, 2,
                            Perm.read | Perm.read_enc, 'AA52'),
                   TestFunc(btp.gatts_set_val, 4, 'FEDCBA9876543210'),
                   TestFunc(btp.gatts_set_enc_key_size, 4, 0x0f),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BV_07_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '1234'),
                   TestFunc(btp.gatts_add_desc, 2, Perm.read, 'AA52'),
                   TestFunc(btp.gatts_set_val, 4,
                            'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF0123456789ABCDEF'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)],
                  verify_wids = {52 : ("Please confirm IUT Handle=\'4\'",
                                        "value=\'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF0123456789ABCDEF\'")}),
        QTestCase("GATT", "TC_GAR_SR_BV_08_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABFFFF'),
                   TestFunc(btp.gatts_add_desc, 2, Perm.read, 'AA52'),
                   TestFunc(btp.gatts_set_val, 4, 'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF0123456789ABCDEF'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)],
                  verify_wids = {52 : ("Please confirm IUT Handle=\'3\'",
                                       "value=\'0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABFFFF\'")}),
        QTestCase("GATT", "TC_GAR_SR_BI_28_C",
                  edit1_wids = {110 : "0004"},
                  cmds = [
                      TestFunc(btp.core_reg_svc_gap),
                      TestFunc(btp.core_reg_svc_gatts),
                      TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                      TestFunc(btp.gatts_add_char, 1,
                               Prop.read, Perm.read, 'AA51'),
                      TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                      TestFunc(btp.gatts_add_desc, 2, 0x00, 'AA52'),
                      TestFunc(btp.gatts_set_val, 4, 'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF0123456789ABCDEF'),
                      TestFunc(btp.gatts_start_server),
                      TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BI_29_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '1234'),
                   TestFunc(btp.gatts_add_desc, 2, Perm.read, 'AA52'),
                   TestFunc(btp.gatts_set_val, 4, 'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF0123456789ABCDEF'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BI_30_C",
                  edit1_wids = {118 : "FFFF"},
                  cmds = [
                      TestFunc(btp.core_reg_svc_gap),
                      TestFunc(btp.core_reg_svc_gatts),
                      TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                      TestFunc(btp.gatts_add_char, 1,
                               Prop.read, Perm.read, 'AA51'),
                      TestFunc(btp.gatts_set_val, 2, '1234'),
                      TestFunc(btp.gatts_add_desc, 2, Perm.read, 'AA52'),
                      TestFunc(btp.gatts_set_val, 4, 'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF0123456789ABCDEF'),
                      TestFunc(btp.gatts_start_server),
                      TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BI_31_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read,
                            'F000AA5104514000B123456789ABCDEF'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_add_desc, 2,
                            Perm.read | Perm.authz, 'AA52'),
                   TestFunc(btp.gatts_set_val, 4, 'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF0123456789ABCDEF'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BI_32_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'F000AA5004514000B123456789ABCDEF'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read,
                            'F000AA5104514000B123456789ABCDEF'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_add_desc, 2,
                            Perm.read | Perm.read_authn,
                            'F000AA5204514000B123456789ABCDEF'),
                   TestFunc(btp.gatts_set_val, 4, 'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF0123456789ABCDEF'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAR_SR_BI_33_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_add_desc, 2,
                            Perm.read | Perm.read_enc, 'AA52'),
                   TestFunc(btp.gatts_set_val, 4, 'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF0123456789ABCDEF'),
                   TestFunc(btp.gatts_set_enc_key_size, 4, 0x0f),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BV_01_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.broadcast | Prop.read | Prop.write_wo_resp,
                            Perm.read | Perm.write, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)],
                  verify_wids = {75 : ("Please confirm IUT Write characteristic handle= '0003'O value= 'BE'O",)}),
        QTestCase("GATT", "TC_GAW_SR_BV_02_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read | Prop.write | Prop.auth_swrite,
                            Perm.read | Perm.write, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_01_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read | Prop.auth_swrite,
                            Perm.read | Perm.write | Perm.write_authn,
                            'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BV_03_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read | Prop.write, Perm.read | Perm.write,
                            'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_02_C",
                  edit1_wids = {118 : "ffff"},
                  cmds = [
                      TestFunc(btp.core_reg_svc_gap),
                      TestFunc(btp.core_reg_svc_gatts),
                      TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                      TestFunc(btp.gatts_add_char, 1,
                               Prop.broadcast | Prop.read | Prop.write_wo_resp,
                               Perm.read | Perm.write, 'AA51'),
                      TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                      TestFunc(btp.gatts_start_server),
                      TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_03_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.broadcast | Prop.read, Perm.read, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_06_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read | Prop.write,
                            Perm.read | Perm.write | Perm.write_enc,
                            'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_set_enc_key_size, 2, 0x0f),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BV_05_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read | Prop.write,
                            Perm.read | Perm.write, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF' * 10),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_07_C",
                  edit1_wids = {118 : "ffff"},
                  cmds = [
                      TestFunc(btp.core_reg_svc_gap),
                      TestFunc(btp.core_reg_svc_gatts),
                      TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                      TestFunc(btp.gatts_add_char, 1,
                               Prop.broadcast | Prop.read | Prop.write_wo_resp,
                               Perm.read | Perm.write, 'AA51'),
                      TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                      TestFunc(btp.gatts_start_server),
                      TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_08_C",
                  edit1_wids = {120 : "0002"},
                  cmds = [
                      TestFunc(btp.core_reg_svc_gap),
                      TestFunc(btp.core_reg_svc_gatts),
                      TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                      TestFunc(btp.gatts_add_char, 1,
                               Prop.broadcast | Prop.read, Perm.read,
                               'AA51'),
                      TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                      TestFunc(btp.gatts_start_server),
                      TestFunc(btp.gap_adv_ind_on)]),
        # TODO: fails cause of ZEP-315
        QTestCase("GATT", "TC_GAW_SR_BI_09_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read | Prop.write,
                            Perm.read | Perm.write | Perm.write_enc,
                            'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF' * 10),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_13_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1, Prop.read | Prop.write,
                            Perm.read | Perm.write | Perm.write_enc, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF' * 10),
                   TestFunc(btp.gatts_set_enc_key_size, 2, 0x0f),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BV_06_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.broadcast | Prop.read | Prop.write,
                            Perm.read | Perm.write, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BV_10_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.broadcast | Prop.read | Prop.write,
                            Perm.read | Perm.write,
                            '2A00'),
                   TestFunc(btp.gatts_set_val, 2, '0123' * 20),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.broadcast | Prop.read | Prop.write,
                            Perm.read | Perm.write,
                            '2A01'),
                   TestFunc(btp.gatts_set_val, 4, '4567' * 20),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_14_C",
                  edit1_wids = {118 : "ffff"},
                  cmds = [
                      TestFunc(btp.core_reg_svc_gap),
                      TestFunc(btp.core_reg_svc_gatts),
                      TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                      TestFunc(btp.gatts_add_char, 1,
                               Prop.broadcast | Prop.read | Prop.write,
                               Perm.read | Perm.write, '2A00'),
                      TestFunc(btp.gatts_set_val, 2, '0123' * 20),
                      TestFunc(btp.gatts_start_server),
                      TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_15_C",
                  edit1_wids = {120 : "0002"},
                  cmds = [
                      TestFunc(btp.core_reg_svc_gap),
                      TestFunc(btp.core_reg_svc_gatts),
                      TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                      TestFunc(btp.gatts_add_char, 1,
                               Prop.broadcast | Prop.read | Prop.write,
                               Perm.read, '2A00'),
                      TestFunc(btp.gatts_set_val, 2, '0123' * 20),
                      TestFunc(btp.gatts_start_server),
                      TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_19_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read | Prop.write,
                            Perm.read | Perm.write | Perm.write_enc,
                            '2A00'),
                   TestFunc(btp.gatts_set_val, 2, '0123'),
                   TestFunc(btp.gatts_set_enc_key_size, 2, 0x0f),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BV_07_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.broadcast | Prop.read | Prop.write,
                            Perm.read | Perm.write,
                            '2A00'),
                   TestFunc(btp.gatts_set_val, 2, '0123'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BV_08_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_add_desc, 2,
                            Perm.read | Perm.write, 'AA52'),
                   TestFunc(btp.gatts_set_val, 4, 'FEDCBA9876543210'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_20_C",
                  edit1_wids = {118 : "FFFF"},
                  cmds = [
                      TestFunc(btp.core_reg_svc_gap),
                      TestFunc(btp.core_reg_svc_gatts),
                      TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                      TestFunc(btp.gatts_add_char, 1,
                               Prop.read, Perm.read, 'AA51'),
                      TestFunc(btp.gatts_set_val, 2, 'DCBA'),
                      TestFunc(btp.gatts_add_desc, 2, 0, 'AA52'),
                      TestFunc(btp.gatts_set_val, 4, 'ABCD'),
                      TestFunc(btp.gatts_start_server),
                      TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_21_C",
                  edit1_wids = {120 : "0004"},
                  cmds = [
                      TestFunc(btp.core_reg_svc_gap),
                      TestFunc(btp.core_reg_svc_gatts),
                      TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                      TestFunc(btp.gatts_add_char, 1,
                               Prop.read, Perm.read, 'AA51'),
                      TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                      TestFunc(btp.gatts_add_desc, 2, Perm.read, 'AA52'),
                      TestFunc(btp.gatts_set_val, 4, 'FEDCBA9876543210'),
                      TestFunc(btp.gatts_start_server),
                      TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_22_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read,
                            'F000AA5104514000B123456789ABCDEF'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_add_desc, 2,
                            Perm.read | Perm.write | Perm.authz, 'AA52'),
                   TestFunc(btp.gatts_set_val, 4, 'FEDCBA9876543210'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_23_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0,
                            'F000AA5004514000B123456789ABCDEF'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read,
                            'F000AA5104514000B123456789ABCDEF'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_add_desc, 2,
                            Perm.read | Perm.write | Perm.write_authn,
                            'F000AA5204514000B123456789ABCDEF'),
                   TestFunc(btp.gatts_set_val, 4, 'FEDCBA9876543210'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_24_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_add_desc, 2,
                            Perm.read | Perm.write | Perm.write_enc, 'AA52'),
                   TestFunc(btp.gatts_set_val, 4, 'FEDCBA9876543210'),
                   TestFunc(btp.gatts_set_enc_key_size, 4, 0x0f),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BV_09_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_add_desc, 2,
                            Perm.read | Perm.write, 'AA52'),
                   TestFunc(btp.gatts_set_val, 4, 'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF0123456789ABCDEF'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_25_C",
                  edit1_wids = {118 : "ABCD"},
                  cmds = [
                      TestFunc(btp.core_reg_svc_gap),
                      TestFunc(btp.core_reg_svc_gatts),
                      TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                      TestFunc(btp.gatts_add_char, 1,
                               Prop.read, Perm.read, 'AA51'),
                      TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                      TestFunc(btp.gatts_add_desc, 2, 0x00, 'AA52'),
                      TestFunc(btp.gatts_set_val, 4, 'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF0123456789ABCDEF'),
                      TestFunc(btp.gatts_start_server),
                      TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_26_C",
                  edit1_wids = {120 : "0004"},
                  cmds = [
                      TestFunc(btp.core_reg_svc_gap),
                      TestFunc(btp.core_reg_svc_gatts),
                      TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                      TestFunc(btp.gatts_add_char, 1,
                               Prop.read, Perm.read, 'AA51'),
                      TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                      TestFunc(btp.gatts_add_desc, 2, Perm.read, 'AA52'),
                      TestFunc(btp.gatts_set_val, 4, 'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF0123456789ABCDEF'),
                      TestFunc(btp.gatts_start_server),
                      TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_27_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_add_desc, 2,
                            Perm.read | Perm.write, 'AA52'),
                   TestFunc(btp.gatts_set_val, 4, 'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF0123456789ABCDEF'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_29_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_add_desc, 2,
                            Perm.read | Perm.write | Perm.authz, 'AA52'),
                   TestFunc(btp.gatts_set_val, 4, 'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF0123456789ABCDEF'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_30_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_add_desc, 2,
                            Perm.read | Perm.write | Perm.write_authn,
                            'AA52'),
                   TestFunc(btp.gatts_set_val, 4, 'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF0123456789ABCDEF'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_31_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_add_desc, 2,
                            Perm.read | Perm.write | Perm.write_enc,
                            'AA52'),
                   TestFunc(btp.gatts_set_val, 4, 'FEDCBA98765432100123456789ABCDEF0123456789ABCDEF0123456789ABCDEF'),
                   TestFunc(btp.gatts_set_enc_key_size, 4, 0x0f),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_32_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read | Prop.write,
                            Perm.read | Perm.write,
                            'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        # TODO: fails cause of ZEP-315
        QTestCase("GATT", "TC_GAW_SR_BI_33_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read | Prop.write,
                            Perm.read | Perm.write,
                            'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF' * 5),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_34_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1, Prop.read,
                            Perm.read, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_add_desc, 2,
                            Perm.read | Perm.write, 'AA52'),
                   TestFunc(btp.gatts_set_val, 4, '1234'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAW_SR_BI_35_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read, 'AA51'),
                   TestFunc(btp.gatts_set_val, 2, '0123456789ABCDEF'),
                   TestFunc(btp.gatts_add_desc, 2,
                            Perm.read | Perm.write, 'AA52'),
                   TestFunc(btp.gatts_set_val, 4, 'FEDCBA9876543210' * 5),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GAN_SR_BV_01_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AAAA'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read | Prop.write | Prop.nofity,
                            Perm.read | Perm.write, 'BBBB'),
                   TestFunc(btp.gatts_set_val, 2, '00'),
                   TestFunc(btp.gatts_add_desc, 2,
                            Perm.read | Perm.write, '2902'),
                   TestFunc(btp.gatts_set_val, 2, '01'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GPA_SR_BV_01_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1, Prop.read,
                            Perm.read, 'BB50'),
                   TestFunc(btp.gatts_set_val, 2, '1234'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)],
                  verify_wids = {102 : ("Attribute Handle = 0x0001",
                                        "Primary Service = 0xAA50")}),
        QTestCase("GATT", "TC_GPA_SR_BV_02_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 1, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1, Prop.read,
                            Perm.read, 'BB50'),
                   TestFunc(btp.gatts_set_val, 2, '1234'),
                   TestFunc(btp.gatts_add_svc, 0, 'AA51'),
                   TestFunc(btp.gatts_add_inc_svc, 1),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)],
                  verify_wids = {102 : ("Attribute Handle = 0x0001",
                                        "Secondary Service = 0xAA50")}),
        QTestCase("GATT", "TC_GPA_SR_BV_03_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 1, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1, Prop.read,
                            Perm.read, 'BB50'),
                   TestFunc(btp.gatts_set_val, 2, '1234'),
                   TestFunc(btp.gatts_add_svc, 0, 'AA51'),
                   TestFunc(btp.gatts_add_inc_svc, 1),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)],
                  verify_wids = {102 : ("Attribute Handle = 0x0005",
                                        "Included Service Attribute handle = 0x0001",
                                        "End Group Handle = 0x0003",
                                        "Service UUID = 0xAA50")}),
        QTestCase("GATT", "TC_GPA_SR_BV_04_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1, Prop.read,
                            Perm.read, 'BB50'),
                   TestFunc(btp.gatts_set_val, 2, '1234'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)],
                  verify_wids = {102 : ("Attribute Handle = 0x0002",
                                        "Properties = 0x02",
                                        "Handle = 0x0003",
                                        "UUID = 0xBB50")}),
        QTestCase("GATT", "TC_GPA_SR_BV_05_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read | Prop.write | Prop.ext_prop,
                            Perm.read | Perm.write, 'BB50'),
                   TestFunc(btp.gatts_set_val, 2, '1234'),
                   TestFunc(btp.gatts_add_desc, 2, Perm.read, '2900'),
                   TestFunc(btp.gatts_set_val, 4, '0100'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)],
                  verify_wids = {102 : ("Attribute Handle = 0x0004",
                                        "Properties = 0x0001")}),
        QTestCase("GATT", "TC_GPA_SR_BV_06_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read, Perm.read, 'BB50'),
                   TestFunc(btp.gatts_set_val, 2, '1234'),
                   TestFunc(btp.gatts_add_desc, 2, Perm.read, '2901'),
                   TestFunc(btp.gatts_set_val, 4, '73616d706c652074657874'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)],
                  verify_wids = {102 : ("Attribute Handle = 0x0004",
                                        "User Description = sample text")}),
        QTestCase("GATT", "TC_GPA_SR_BV_07_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1,
                            Prop.read | Prop.write | Prop.nofity,
                            Perm.read, 'BB50'),
                   TestFunc(btp.gatts_set_val, 2, '1234'),
                   TestFunc(btp.gatts_add_desc, 2, Perm.read | Perm.write,
                            '2902'),
                   TestFunc(btp.gatts_set_val, 4, '0000'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)],
                  verify_wids = {102 : ("Attribute Handle = 0x0004",
                                        "Properties = 0x0000")}),
        QTestCase("GATT", "TC_GPA_SR_BV_08_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1, Prop.broadcast | Prop.read,
                            Perm.read, 'BB50'),
                   TestFunc(btp.gatts_set_val, 2, '1234'),
                   TestFunc(btp.gatts_add_desc, 2,
                            Perm.read | Perm.write | Perm.write_authn | \
                            Perm.authz,
                            '2903'),
                   TestFunc(btp.gatts_set_val, 4, '0000'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)],
                  verify_wids = {102 : ("Attribute Handle = 0x0004",
                                        "Properties = 0x0000")}),
        QTestCase("GATT", "TC_GPA_SR_BV_11_C",
                  [TestFunc(btp.core_reg_svc_gap),
                   TestFunc(btp.core_reg_svc_gatts),
                   TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                   TestFunc(btp.gatts_add_char, 1, Prop.read | Prop.write,
                            Perm.read, 'BB50'),
                   TestFunc(btp.gatts_set_val, 2, '65'),
                   TestFunc(btp.gatts_add_desc, 2, Perm.read, '2904'),
                   TestFunc(btp.gatts_set_val, 4, '04000127010100'),
                   TestFunc(btp.gatts_add_char, 1, Prop.read | Prop.write,
                            Perm.read, 'BB51'),
                   TestFunc(btp.gatts_set_val, 5, '1234'),
                   TestFunc(btp.gatts_add_desc, 5, Perm.read, '2904'),
                   TestFunc(btp.gatts_set_val, 7, '06001027010200'),
                   TestFunc(btp.gatts_add_char, 1, Prop.read | Prop.write,
                            Perm.read, 'BB52'),
                   TestFunc(btp.gatts_set_val, 8, '01020304'),
                   TestFunc(btp.gatts_add_desc, 8, Perm.read, '2904'),
                   TestFunc(btp.gatts_set_val, 10, '08001727010300'),
                   TestFunc(btp.gatts_add_char, 1, Prop.read | Prop.write,
                            Perm.read, 'BB52'),
                   TestFunc(btp.gatts_set_val, 11, '65123401020304'),
                   TestFunc(btp.gatts_add_desc, 11, Perm.read, '2905'),
                   TestFunc(btp.gatts_set_val, 13, '040007001000'),
                   TestFunc(btp.gatts_start_server),
                   TestFunc(btp.gap_adv_ind_on)]),
        QTestCase("GATT", "TC_GPA_SR_BV_12_C",
                   [TestFunc(btp.core_reg_svc_gap),
                    TestFunc(btp.core_reg_svc_gatts),
                    TestFunc(btp.gatts_add_svc, 0, 'AA50'),
                    TestFunc(btp.gatts_add_char, 1, Prop.read, Perm.read,
                             'BB50'),
                    TestFunc(btp.gatts_set_val, 2, '1234'),
                    TestFunc(btp.gatts_add_desc, 2, Perm.read, '2904'),
                    TestFunc(btp.gatts_set_val, 4, '0600A327010100'),
                    TestFunc(btp.gatts_start_server),
                    TestFunc(btp.gap_adv_ind_on)],
                   verify_wids = {104 : ("Value = \'1234\'",
                                         "Attribute Handle = 0x0004",
                                         "Format = 0x06",
                                         "Exponent = 0",
                                         "Uint = 0x27A3",
                                         "Namespace = 0x01",
                                         "Description = 0x0001")}),
    ]

    return test_cases

def test_cases_client():
    """Returns a list of GATT Client test cases"""

    zephyrctl = get_zephyr()

    test_cases = [
        #QTestCase("GATT", "TC_GAR_CL_BV_01_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_01_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_02_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_03_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_04_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_05_C",
        #QTestCase("GATT", "TC_GAR_CL_BV_04_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_12_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_13_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_14_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_15_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_16_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_17_C",
        #QTestCase("GATT", "TC_GAR_CL_BV_05_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_18_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_19_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_20_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_21_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_22_C",
        #QTestCase("GATT", "TC_GAR_CL_BV_06_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_23_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_24_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_25_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_26_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_27_C",
        #QTestCase("GATT", "TC_GAR_CL_BV_07_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_28_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_29_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_30_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_31_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_32_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_33_C",
        #QTestCase("GATT", "TC_GAR_CL_BI_35_C",
    ]

    return test_cases

def test_cases():
    """Returns a list of GATT test cases"""
    test_cases = test_cases_server()
    test_cases += test_cases_client()

    return test_cases

def main():
    """Main."""
    import sys
    import ptsprojects.zephyr.iutctl as iutctl

    iutctl.init_stub()

    # to be able to successfully create ZephyrCtl in QTestCase
    iutctl.ZEPHYR_KERNEL_IMAGE = sys.argv[0]

    test_cases_ = test_cases()

    for test_case in test_cases_:
        print
        print test_case

        if test_case.edit1_wids:
            print "edit1_wids: %r" % test_case.edit1_wids

        if test_case.verify_wids:
            print "verify_wids: %r" % test_case.verify_wids

        for index, cmd in enumerate(test_case.cmds):
            str_cmd = str(cmd)

            if isinstance(cmd, TestFunc):
                if cmd.func == btp.gatts_add_char:
                    str_cmd += ", Properties: %s" % Prop.decode(cmd.args[1])
                    str_cmd += ", Permissions: %s" % Perm.decode(cmd.args[2])
                elif cmd.func == btp.gatts_add_desc:
                    str_cmd += ", Permissions: %s" % Perm.decode(cmd.args[1])

            print "%d) %s" % (index, str_cmd)

if __name__ == "__main__":
    main()
