#
# auto-pts - The Bluetooth PTS Automation Framework
#
# Copyright (c) 2017, Codecoup.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#

"""MESH test cases"""

try:
    from ptsprojects.testcase import TestCase, TestCmd, TestFunc, \
        TestFuncCleanUp
    from ptsprojects.zephyr.ztestcase import ZTestCase

except ImportError:  # running this module as script
    import sys
    import os
    # to be able to locate the following imports
    sys.path.append(os.path.dirname(os.path.realpath(__file__)) + "/../..")

    from ptsprojects.testcase import TestCase, TestCmd, TestFunc, \
        TestFuncCleanUp
    from ptsprojects.zephyr.ztestcase import ZTestCase

import ptsprojects.zephyr.btp


def test_cases(pts):
    """Returns a list of MESH test cases
    pts -- Instance of PyPTS"""

    pts_bd_addr = pts.q_bd_addr

    pre_conditions=[TestFunc(btp.core_reg_svc_gap),
                    TestFunc(btp.gap_read_ctrl_info),
                    TestFunc(btp.wrap, pts.update_pixit_param, "MESH",
                             "TSPX_bd_addr_iut", btp.get_stored_bd_addr),]

    test_cases = [
        ZTestCase("MESH", "MESH/NODE/BCN/SNB/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/BCN/SNB/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/AKL/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/AKL/BI-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/AKL/BI-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/AKL/BI-04-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/AKL/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/AKL/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/AKL/BV-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/CFGF/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/CFGF/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/CFGR/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/CFGR/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/COMP/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/DTTL/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/DTTL/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/GPXY/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/GPXY/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/GPXY/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/HBP/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/HBP/BI-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/HBP/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/HBP/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/HBP/BV-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/HBP/BV-05-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/HBP/BV-06-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/HBP/BV-07-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/HBS/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/HBS/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/HBS/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/HBS/BV-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/HBS/BV-04-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/MAKL/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/MAKL/BI-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/MAKL/BI-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/MAKL/BI-04-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/MAKL/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/MAKL/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/MP/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/MP/BI-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/MP/BI-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/MP/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/MP/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/NID/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/NID/BI-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/NID/BI-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/NID/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/NID/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/NID/BV-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/NKL/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/NKL/BI-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/NKL/BI-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/NKL/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/NKL/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/NKL/BV-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/NKL/BV-04-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/NTX/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/RST/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/SL/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/SL/BI-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/SL/BI-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/SL/BI-04-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/SL/BI-05-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/SL/BI-06-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/SL/BI-07-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/SL/BI-08-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/SL/BI-09-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/SL/BI-10-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/SL/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/SL/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/SL/BV-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/SNBP/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/CFG/SNBP/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/FRND/LPN/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/FRND/LPN/BI-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/FRND/LPN/BI-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/FRND/LPN/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/FRND/LPN/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/FRND/LPN/BV-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/FRND/LPN/BV-04-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/FRND/LPN/BV-05-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/FRND/LPN/BV-06-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/FRND/LPN/BV-07-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/FRND/LPN/BV-08-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/IVU/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/IVU/BI-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/IVU/BI-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/IVU/BI-04-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/IVU/BI-05-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/IVU/BI-06-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/IVU/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/IVU/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/IVU/BV-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/IVU/BV-04-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/IVU/BV-05-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/KR/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/KR/BI-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/KR/BI-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/KR/BI-04-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/KR/BI-05-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/KR/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/KR/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/KR/BV-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/MPS/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/MPS/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/MPS/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/MPS/BV-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/MPS/BV-04-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/MPS/BV-05-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/MPS/BV-06-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/MPS/BV-07-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/MPS/BV-08-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/MPS/BV-09-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/MPS/BV-10-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/NET/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/NET/BI-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/NET/BI-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/NET/BI-04-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/NET/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/NET/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/NET/BV-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/NET/BV-04-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/NET/BV-05-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/NET/BV-06-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/NET/BV-07-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/NET/BV-08-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/NET/BV-09-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/NET/BV-10-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/NET/BV-11-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/NET/BV-13-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/NET/BV-14-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/PBADV/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/PBADV/BI-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/PBADV/BI-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/PBADV/BI-04-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/PBADV/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/PBADV/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/PBADV/BV-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/PBADV/BV-04-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/PROV/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/PROV/BI-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/PROV/UPD/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/PROV/UPD/BV-07-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/PROV/UPD/BV-09-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/PROV/UPD/BV-10-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/PROV/UPD/BV-11-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/RLY/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/RLY/BI-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/RLY/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/RLY/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/TNPT/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/TNPT/BI-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/TNPT/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/TNPT/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/TNPT/BV-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/TNPT/BV-04-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/TNPT/BV-05-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/TNPT/BV-06-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/TNPT/BV-07-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/TNPT/BV-08-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/TNPT/BV-09-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/TNPT/BV-10-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/TNPT/BV-11-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/TNPT/BV-12-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/NODE/TNPT/BV-13-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/HM/ATS/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/HM/CFS/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/HM/CFS/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/HM/HPS/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/HM/RFS/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/HM/RFS/BI-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/HM/RFS/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/HM/RFS/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/HM/RFS/BV-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/MPXS/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/MPXS/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/MPXS/BV-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/MPXS/BV-04-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/MPXS/BV-05-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/MPXS/BV-06-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/MPXS/BV-07-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/MPXS/BV-08-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/MPXS/BV-09-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/PROX/BI-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/PROX/BV-01-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/PROX/BV-02-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/PROX/BV-03-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/PROX/BV-04-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/PROX/BV-05-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/PROX/BV-06-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/PROX/BV-07-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/PROX/BV-08-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/PROX/BV-09-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/PROX/BV-10-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/PROX/BV-11-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/PROX/BV-12-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/PROX/BV-13-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
        ZTestCase("MESH", "MESH/SR/PROX/BV-14-C", cmds=pre_conditions,
            generic_wid_hdl=mesh_wid_hdl),
    ]

    return test_cases


def main():
    """Main."""
    import ptsprojects.zephyr.iutctl as iutctl
    class pts: pass
    pts.q_bd_addr = "AB:CD:EF:12:34:56"

    iutctl.init_stub()

    test_cases_ = test_cases(pts)

    for test_case in test_cases_:
        print
        print test_case

        if test_case.edit1_wids:
            print "edit1_wids: %r" % test_case.edit1_wids

        if test_case.verify_wids:
            print "verify_wids: %r" % test_case.verify_wids

        for index, cmd in enumerate(test_case.cmds):
            print "%d) %s" % (index, cmd)

if __name__ == "__main__":
    main()
